# Generated by Django 4.2.9 on 2026-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_user_school_user_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key e.g. school_dashboard, manage_teachers', max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='site_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'site_images',
                'ordering': ['key'],
            },
        ),
    ]
