# Generated by Django 4.2.9 on 2026-02-13 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School that owns this image (null = global default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='key',
            field=models.CharField(help_text='Unique key e.g. school_dashboard, manage_teachers', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='siteimage',
            unique_together={('school', 'key')},
        ),
    ]
