# Generated by Django 4.2.9 on 2026-02-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='exams.chapter')),
            ],
            options={
                'db_table': 'study_materials',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('formula', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_concepts', to='study_material.studymaterial')),
            ],
            options={
                'db_table': 'key_concepts',
                'ordering': ['order'],
            },
        ),
    ]
