# Generated by Django 4.2.9 on 2026-02-12 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School that owns this question (null = global)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='teacher_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='teacher_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='teacher_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexam',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this exam belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='exam_papers/%Y/%m/')),
                ('total_marks', models.IntegerField(default=50)),
                ('extracted_text', models.TextField(blank=True)),
                ('questions_generated', models.BooleanField(default=False)),
                ('generation_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.chapter')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('num_questions', models.IntegerField(default=29)),
                ('total_marks', models.IntegerField(default=50)),
                ('duration_minutes', models.IntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
                ('chapters', models.ManyToManyField(blank=True, to='exams.chapter')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams_school', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assigned_exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userexam',
            name='assigned_exam',
            field=models.ForeignKey(blank=True, help_text='The assigned exam this attempt is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_exams', to='exams.assignedexam'),
        ),
    ]
